language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: 7.0

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - php bin/benchmark --rows=100  --cells=10  --iteration=3
    - php bin/benchmark --rows=200000  --cells=5 --iteraotion=3