language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

script:
  - php bin/benchmark --iteration=3 --rows=100    --cells=10
  - php bin/benchmark --iteration=3 --rows=200000 --cells=5