language: php

php:
    - 5.5
    - 5.6
    - hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - php bin/benchmark --rows=100
    - php bin/benchmark --rows=200000